=pod

=encoding utf-8

=head1 NAME

mhping - Multiple host ping

=head1 SYNOPSIS

    mhping [options] [systems...]

=head1 DESCRIPTION

mhping is a sysadmin tool that allows You to simultaneously check multiple
hosts for availability. Target hosts can be specified one per line in several
ways (in order of precedence):

=over 4

=item 1.
from command line

=item 2.
from stdin

=item 3.
from a file using the C<-f> option

=back

=head1 OPTIONS

=over 4

=item -f, --filename

Read list of targets from file or stdin if C<-> is specified as the filename.

=item -h, --help

Print usage message.

=item -v, --version

Print C<mhping> version information.

=back

=head1 BUGS

Please report bugs on github: L<https://github.com/arpadszasz/mhping/issues>

=head1 AUTHORS

Árpád Szász

=head1 SEE ALSO

L<ping(8)>
L<fping(8)>
L<mtr(8)>
L<threads>
L<threads::shared>
L<Thread::Queue>

=cut
