=pod

=encoding utf-8

=head1 NAME

mhping - Multiple host ping

=head1 SYNOPSIS

    mhping [options]

=head1 DESCRIPTION

mhping is a sysadmin tool that allows You to simultaneously check multiple hosts
for availability.

=head1 OPTIONS

=over 4

=item -f, --filename

Read list of targets from file. Targets should be specified one per line.

=item -h, --help

Print usage message.

=item -v, --version

Print C<mhping> version information.

=back

=head1 BUGS

Please report bugs on github: L<https://github.com/arpadszasz/mhping/issues>

=head1 AUTHORS

Árpád Szász

=head1 SEE ALSO

L<threads>
L<threads::shared>
L<Thread::Queue>

=cut
